apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-cve-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-cve-service
    app.kubernetes.io/part-of: exhort
  name: exhort-cve-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: exhort-cve-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: exhort-cve-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort-cve-service@sha256:41cde8466a37e570b83d0ca369723ae9ad9ba2444d100d001fefec62c8a57800
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
