apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort-cve-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort-cve-service
    app.kubernetes.io/part-of: exhort
  name: exhort-cve-service
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: exhort-cve-service
status:
  loadBalancer: {}
