apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: onguard
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/onguard@sha256:9365e10d2fd262b866f14e46545528bdd78972b9de28259b1771f2a6fa948dbe
        name: my-java-quarkus
        resources: {}
status: {}
