apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: onguard
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/onguard@sha256:eda9927124a40f7c868d73c8de9f59e88c2c07115b6df3181f707934c87cea7e
        name: my-java-quarkus
        resources: {}
status: {}
