apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: onguard
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: onguard
    app.kubernetes.io/part-of: exhort
  name: onguard
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: onguard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: onguard
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/onguard@sha256:846e713d94955c93c7ab687eab7b5e7e5a666236c073a21880dbf07a9dc0975c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
