apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: onguard
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: onguard
    app.kubernetes.io/part-of: exhort
  name: onguard
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: onguard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: onguard
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/onguard@sha256:50f5fdcbeb21849e4ee6e64683f9a451ca492051b1244f7c291ee0ea30317c3b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
