apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: exhort
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort@sha256:f713324ac28195126ee6aef774250748ca8e935100039c4a08465970247cadb1
        name: exhort
        resources: {}
status: {}
