apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: exhort
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort@sha256:4f7f95d94b07fe2e21ffc02129e86be44081a4cc58e33258aaec1b37aa8f62bb
        name: exhort
        resources: {}
status: {}
