apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: exhort
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort@sha256:7bdac275f15f255bc0bef1cdd6691a6ab3dedb7bf2336575f659328ab8cb446b
        name: exhort
        resources: {}
status: {}
