apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: exhort
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort@sha256:b1286ba79eaed32121207bd76a6acb0dc40716c4087891d9984906593230639b
        name: exhort
        resources: {}
status: {}
